import { useEffect, useState } from 'react'
import { useExecutiveData } from '../hooks/useExecutiveData'
import { BrandLockup } from './BrandMark'
import { BriefingStudio } from './BriefingStudio'
import { DecisionLedger } from './DecisionLedger'
import { EvidenceCasefile } from './EvidenceCasefile'
import { EvidenceLedger } from './EvidenceLedger'
import { OverviewPanel } from './OverviewPanel'
import { ScenarioLab } from './ScenarioLab'

const sections = [
  ['overview', 'Overview', '01'],
  ['evidence', 'Evidence ledger', '02'],
  ['casefile', 'Evidence casefile', '03'],
  ['decisions', 'Decision record', '04'],
  ['briefing', 'Briefing room', '05'],
  ['scenario', 'Scenario lab', '06'],
]

const viewCopy = {
  overview: ['Signal desk', 'What is currently worth a human look.'],
  evidence: ['Evidence ledger', 'Every accepted predictive relationship, inspectable.'],
  casefile: ['Evidence casefile', 'Replay the data, test family, and model boundary behind one action.'],
  decisions: ['Decision record', 'Human-owned actions and measured outcomes.'],
  briefing: ['Briefing room', 'Ask only what stored evidence can support.'],
  scenario: ['Scenario lab', 'A bounded, deterministic marketing-spend forecast.'],
}

function StatusNotice({ data }) {
  const notices = [
    data.errors.connection && ['Connection issue', data.errors.connection],
    data.coldBlocked && ['Cold path pending recovery', data.status.last_cold_error],
    data.errors.evidence && ['Evidence analysis unavailable', data.errors.evidence],
    data.errors.casefile && ['Evidence casefile unavailable', data.errors.casefile],
    data.errors.resilience && ['Evidence resilience unavailable', data.errors.resilience],
    data.errors.decisions && ['Decision workflow unavailable', data.errors.decisions],
    data.errors.executive && ['Executive workflow unavailable', data.errors.executive],
  ].filter(Boolean)

  if (notices.length === 0) return null

  return (
    <div className="workspace-notices" aria-live="polite">
      {notices.map(([title, detail]) => <p key={title}><strong>{title}.</strong> {detail}</p>)}
    </div>
  )
}

export function AppWorkspace() {
  const [activeSection, setActiveSection] = useState('overview')
  const [selectedCasefileSignalId, setSelectedCasefileSignalId] = useState(null)
  const data = useExecutiveData()
  const [heading, description] = viewCopy[activeSection]
  const casefileSignalId = selectedCasefileSignalId ?? data.signals[0]?.id ?? null

  useEffect(() => {
    if (
      activeSection === 'casefile'
      && casefileSignalId
      && data.casefile?.signal?.id !== casefileSignalId
      && !data.busy.casefile
    ) {
      data.loadCasefile(casefileSignalId)
    }
    if (
      activeSection === 'casefile'
      && casefileSignalId
      && data.resilienceSignalId !== casefileSignalId
      && !data.busy.resilience
    ) {
      data.loadResilience(casefileSignalId)
    }
  }, [activeSection, casefileSignalId, data.busy.casefile, data.busy.resilience, data.casefile?.signal?.id, data.resilienceSignalId, data.loadCasefile, data.loadResilience])

  function openCasefile(signalId) {
    setSelectedCasefileSignalId(signalId)
    setActiveSection('casefile')
  }

  return (
    <div className="workspace-shell">
      <header className="workspace-header">
        <a className="brand-link" href="/" aria-label="MetricThread home"><BrandLockup inverse /></a>
        <div className="workspace-context"><span>South Growth Business Unit</span><i aria-hidden="true" /> <span>Executive view</span></div>
        <div className="workspace-live"><span className={data.isRunning ? 'pulse-dot' : 'idle-dot'} aria-hidden="true" /> {data.status?.simulation_label ?? 'connecting to simulation'}</div>
      </header>

      <div className="workspace-frame">
        <aside className="workspace-sidebar">
          <p className="sidebar-label">Intelligence workspace</p>
          <nav aria-label="Workspace sections">
            {sections.map(([id, label, number]) => (
              <button
                className={activeSection === id ? 'workspace-nav-item selected' : 'workspace-nav-item'}
                key={id}
                type="button"
                onClick={() => setActiveSection(id)}
                aria-current={activeSection === id ? 'page' : undefined}
              >
                <span>{number}</span>{label}
              </button>
            ))}
          </nav>
          <div className="sidebar-footnote">
            <span>MODE</span>
            <strong>{data.readOnlyDemo ? 'READ-ONLY DEMO' : 'WORKSPACE'}</strong>
            <p>All observed values are generated by a seeded synthetic simulation.</p>
          </div>
        </aside>

        <main className="workspace-main">
          <section className="view-heading">
            <div>
              <p className="kicker">{activeSection === 'overview' ? 'Current operating picture' : 'MetricThread / auditable intelligence'}</p>
              <h1>{heading}</h1>
              <p>{description}</p>
            </div>
            <div className="heading-actions">
              {data.readOnlyDemo && <span className="read-only-flag">Read-only judge demo</span>}
              <button type="button" className="outline-action" onClick={data.startSimulation} disabled={data.isRunning || data.busy.simulation}>
                {data.isRunning ? 'Simulation running' : data.busy.simulation ? 'Starting…' : 'Run live simulation'}
              </button>
            </div>
          </section>

          <StatusNotice data={data} />
          {data.readOnlyDemo && (
            <p className="demo-disclosure">
              Protected actions preserve the demo’s persisted evidence and decision history. Scenario forecasts are safe, ephemeral explorations.
            </p>
          )}

          {activeSection === 'overview' && <OverviewPanel data={data} onNavigate={setActiveSection} />}
          {activeSection === 'evidence' && <EvidenceLedger data={data} onOpenCasefile={openCasefile} />}
          {activeSection === 'casefile' && (
            <EvidenceCasefile
              casefile={data.casefile}
              error={data.errors.casefile}
              loading={data.busy.casefile}
              resilience={data.resilienceSignalId === casefileSignalId ? data.resilience : null}
              resilienceError={data.errors.resilience}
              resilienceLoading={data.busy.resilience}
              selectedSignalId={casefileSignalId}
              signals={data.signals}
              onSelectSignal={setSelectedCasefileSignalId}
            />
          )}
          {activeSection === 'decisions' && <DecisionLedger data={data} />}
          {activeSection === 'briefing' && <BriefingStudio data={data} />}
          {activeSection === 'scenario' && <ScenarioLab data={data} />}
        </main>
      </div>
    </div>
  )
}
